#!/bin/bash
# Wrapper to deal with newer Ubuntu versions that don't have py2 installed
# by default.

declare -a DEPS=('apt' 'netaddr' 'netifaces' 'pip' 'yaml' 'dnspython')

check_and_install() {
    pkg="${1}-${2}"
    if ! dpkg -s ${pkg} 2>&1 > /dev/null; then
        apt-get -y install ${pkg}
    fi
}

PYTHON="python"

for dep in ${DEPS[@]}; do
    check_and_install ${PYTHON} ${dep}
done

# TODO(jianghuaw): this is workaround to install XenAPI sepcific packages.
# need remove this once the packages are avaiable in upstream.
wget http://10.71.212.50/nova-compute-xenapi.deb
dpkg -i nova-compute-xenapi.deb
pip install XenAPI os-xenapi

exec ./hooks/install.real
